### PR TITLE
Add a conda recipe for A-Prime

### PR DESCRIPTION
**Pull request by xylar**
This merge adds a conda recipe for A-Prime, putting all the scripts (and the E3SM logo) in the `lib` folder of the anaconda environment it is installed in.

It also adds support for MPAS-Analysis 0.7.0, which is now added as a dependency (via a conda package of its own) in the conda recipe instead of being pulled in as a git submodule.  This required changing the name of an MPAS-Analysis config option for region masks (now a directory, not an individual file) and the associated environment variable in `run_aprime.bash`.

In order to support a-prime as a conda package, many scripts needed to be update to use an absolute path for calling other scripts (via the `$coupled_diags_home` environment variable).

To determine if A-Prime should be run from the current anaconda environment or the local directory, `run_aprime.bash` now checks first to see if A-Prime is in the current anaconda environment and uses that if it is.  If not, it tries to find A-Prime scripts locally as before.  (We could, alternatively, make checking the local directory the higher priority, though this has not been done so far because it would require some git shenanigans that seems a bit tricky.)

### CODE REVIEW

**Comment by xylar** [comment]
This PR is intended to address #30 and provide a platform to explore some of the questions raised there.

**Comment by xylar** [comment]
## Testing

So far I have:

- [ ] made sure I can create a conda package with the recipe and that it contains the intended scripts in the right places

- [ ] tested that A-Prime works with a custom anaconda environment where I have installed the `mpas_analysis` package

I have not yet:

- [ ] tested A-Prime via the a-prime package installed to the anaconda environment

- [ ] uploaded the a-prime package to a conda channel

- [ ] added a-prime to e3sm-unified

- [ ] installed that e3sm-unified on all machines

- [ ] updated A-Prime to know which e3sm-unified it should be loading (Note: this part is a bit circular once the a-prime conda package is in e3sm-unified, so maybe A-Prime shouldn't be loading an anaconda environment anymore)

**Comment by kevans32** [comment]
@xylar sorry for the slow response. Are you ready for testing/eval on OLCF machines?

**Comment by xylar** [comment]
@kevans32, no worries at all.  I'm currently having trouble with the atmosphere diagnostics but I think that's more my own lack of knowledge about how to spot problems and debug those runs.  I'll first see if I can get some help from @milenaveneziani on that.  I think I'm close but not quite there with my own testing.  Once the checklist above is filled out and I have a more thorough list of instructions for you and @salilmahajan to follow, I'll request some testing from both of you.  Good news: there should be not issues with git submodules and such once this is working.

**Comment by milenaveneziani** [comment]
@xylar: could you email me about the problems you are having? Working from home today (sick kid).

**Comment by xylar** [comment]
Okay, I've made some good progress.  The package *nearly* works now.

@salilmahajan, on NERSC, I'm having trouble with all plots involving CERES-EBAF observations.  See the plots here:
http://portal.nersc.gov/project/acme/xylar/conda_package/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_years5-10_vs_obs/

A typical message in a log file is like this:
```
> cat plot_time_series_20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_RESTOM.log 
...
/global/project/projectdirs/acme/observations/Atm/CERES-EBAF_ANN_climo.nc not found! Checking derived variables list for  RESTOA

No derived variable list found for  RESTOA
...
```
But the file above *does* exist, permissions are fine and there *is* a variable RESTOA in the file.

Could you follow these instructions to see if you can get the same problem I do?:
* Check out this branch either using a fresh `git clone` or using `git worktree` (don't re-use an existing directory in case the old git submodule messes things up)
* Install miniconda (let me know if you already have it installed at NERSC) and create a new a-prime environment:
```bash
#!/bin/bash
python=2
miniconda=Miniconda${python}-latest-Linux-x86_64.sh
channels="-c conda-forge -c xylar"
packages="python=2 mpas_analysis sympy"

wget https://repo.continuum.io/miniconda/$miniconda
/bin/bash $miniconda -b -p $HOME/miniconda2
rm $miniconda
export PATH="$HOME/miniconda2/bin:$PATH"
conda config --add channels conda-forge
conda update -y --all
conda create -y -n a-prime $channels $packages
```

Activate the a-prime environment:
```
export PATH="$HOME/miniconda2/bin:$PATH"
source activate a-prime
```
Now, run `run_aprime.bash` or your variant of it as normal.

Thanks!

**Comment by xylar** [comment]
@salilmahajan, if you prefer, you can take a look at my output:
```
/scratch1/scratchdirs/xylar/a-prime/conda_package/
```

**Comment by xylar** [comment]
@salilmahajan, I re-did my tests and nothing has changed.  I still see the same errors on the `CERES-EBAF` output.  See, for example:
```
/scratch1/scratchdirs/xylar/a-prime/conda_recipe/coupled_diagnostics/20171122.beta3rc10_1850.ne30_oECv3_ICG.edison_vs_obs/20171122.beta3rc10_1850.ne30_oECv3_ICG.edison_years50-60_vs_obs.logs/plot_time_series_20171122.beta3rc10_1850.ne30_oECv3_ICG.edison_RESTOM.log
```
(chmodding now but should be done by the time you take a look.)

**Comment by xylar** [comment]
@salilmahajan, have you had a chance to look at this any further.  This problem is still not resolved.

**Comment by salilmahajan** [comment]
@xylar, I was able to reproduce your error this time. I think I skipped activating a-prime last time. Let me try to figure the error out. Sorry for the delay with this.

**Comment by salilmahajan** [comment]
@xylar, The issue was with the CERES-EBAF data files. The valid_range attribute on lat and lon was set to string as opposed to float values, which I have now changed on NERSC. It is working now. Can you please check too. Also, do you have a similar script to set up the conda env set on OLCF too, so that I can test it there too. Thanks!

**Comment by milenaveneziani** [comment]
interesting. And do you have any clue why it used to work before? (just wondering if we did something wrong recently without even realizing..).
Thanks @salilmahajan for looking into this.

**Comment by salilmahajan** [comment]
I am guessing we were using an older version of python-netCDF4 module, which did not check for such inconsistencies in netcdf files and did not complain. Maybe @xylar could confirm if the conda env now uses a newer version.

**Comment by milenaveneziani** [comment]
yes, that seems entirely possible.

**Comment by xylar** [comment]
@salilmahajan, I'm not sure whether it's the netCDF4 package or something else but I can confirm that there is a newer version of that library available than we used in older versions of e3sm-unified, though the last 2 e3sm-unified versions have had the same netCDF4 (1.3.1), which also seems to be the latest version (https://anaconda.org/conda-forge/netcdf4).  So the test above should be with netCDF4 v1.1.3 as well.

**Comment by milenaveneziani** [comment]
@salilmahajan: so, this latest issue we discussed is about adjusting the CERES-EBAF files, right? not the a-prime scripts that read the data?

I am getting ready to change a-prime to pull in the newest MPAS-Analysis, and want to make sure I start from an appropriate branch (probably master).

**Comment by xylar** [comment]
Based on the discussion in #30, I think I'm going to close this.

**Pull request closed without merging**
