### PR TITLE
Add support for python 3

### PR DESCRIPTION
**Pull request by xylar**
Makes several different changes to make sure we can support python 3
* adds a futures statement to each python file so print is a function, division is float, etc. by default
* change print statements to be functions
* import `ConfigParser` from the `six` package for backward compatibility in python 3
* cast iterators to lists (e.g. `range()` when it's assigned to a variable rather than used in a `for` statement)
* integer division is performed with `//` rather than `/` (which performs float division even if the denominator is an integer)
* since explicit string expressions (between quotes) are now `unicode` objects in python 2, they occasionally need to be cast back to `str` before being past to code that does not expect `unicode` objects.

### CODE REVIEW

**Comment by xylar** [comment]
This PR branches off of #18 so shouldn't be merged until after that PR.

**Comment by xylar** [comment]
## Testing

I ran on the `20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison` simulation output and see only the same errors (related to #19) that we have already seen for `origin/master`.

**Comment by milenaveneziani** [comment]
@xylar: if we succeed in merging #18, I would test this immediately after (I'll just wait for you to rebase?).
so that I can start working on integrating MPAS-Analysis v0.6.

**Comment by xylar** [comment]
@milenaveneziani, I will rebase this today and test with python 3.  I'll take the "don't merge" flag off as soon as my tests pass.

**Comment by xylar** [comment]
I'm testing with a python 3 install that can be accessed on Edison with:
```
export PATH=/global/project/projectdirs/acme/software/anaconda_envs/edison_mpas_analysis_py3/bin:$PATH
```
Under python 3, I'm seeing errors when trying to read NetCDF files:
```
Traceback (most recent call last):
  File "/global/u2/x/xylar/acme_work/a-prime/add_python3_support/python/read_climo_file.py", line 41, in read_climo_file
    lat = f.variables['lat'][:]
  File "netCDF4/_netCDF4.pyx", line 3999, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 4126, in netCDF4._netCDF4.Variable._toma
  File "netCDF4/_netCDF4.pyx", line 4257, in netCDF4._netCDF4.Variable._check_safecast
ValueError: could not convert string to float: 'degrees_south'
```
I'm not sure these errors are directly related to python 3, they may have to do with either a new version of netcdf4 or of NCO.  The cause of the error is that ncclimo (or perhaps some other step -- I'm not at all clear on the inner workings of the atmosphere diagnostics) seems so be adding an attribute for the valid range that incorrectly comes from the description of the variable and does not provide a numerical range:
```
> ncdump -h /global/project/projectdirs/acme/observations/Atm/CERES-EBAF_ANN_climo.nc | more
...
	float lon(lon) ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:valid_range = "degrees_east" ;
	float lat(lat) ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:valid_range = "degrees_south" ;
		lat:actual_range = -89.5f, 89.5f ;
...
```
Note the `valid_range` in `lat` and `lon` above.  @salilmahajan, is this something you can investigate? If ncclimo or another NCO step is the cause, we might need to bring @czender into the conversation but we should probably find out first if that's the case.

**Comment by xylar** [comment]
I created a python 2 environment that's the same as my python 3 environment in terms of having the latest versions of all the required packages (though I haven't carefully checked that the packages all have the same version).  The python 2 environment doesn't have any trouble with the weird `valid_range` issue above, so it must be something in the python 3 version of netcdf4 that is pickier about valid range.

I'm seeing some other errors on the python 3 side but not under python 2:
```
  File "python/plot_climo.py", line 194, in <module>
    'max = '  + str(round(field_max, 2))
TypeError: type numpy.ndarray doesn't define __round__ method
```
and
```
  File "/global/u2/x/xylar/acme_work/a-prime/add_python3_support/python/read_climo_file.py", line 45, in read_climo_file
    area = f.variables['area'][:]
KeyError: 'area'
...
  File "/global/u2/x/xylar/acme_work/a-prime/add_python3_support/python/read_climo_file.py", line 47, in read_climo_file
    gw = f.variables['gw'][:]
KeyError: 'gw'
```

**Comment by xylar** [comment]
@milenaveneziani, I would say at this point that it doesn't make sense to wait on this PR to start the v0.6 integration work.  There are clearly some issues here that will take some time to work out and I don't have time to figure them out right now.  Anyway, since we only added python 3 support to MPAS-Analysis after v0.6, it might make more sense to worry about python 3 support in a-prime when we merge MPAS-Analysis v0.7.

Hopefully, you will only need to change the one python file for creating the config file for ocn/ice diagnostics so it won't be too much work to merge your changes into this branch later on.

**Comment by milenaveneziani** [comment]
ok, I will work on the v0.6 stuff today.

**Comment by salilmahajan** [comment]
@xylar, @milenaveneziani: About valid_range: I have seen this before, but I cannot recall when/where. Editing the netcdf file to include a numerical valid_range will fixes that problem, if I remember correctly.

**Comment by xylar** [comment]
The `round` issue is odd.  One fix would be to use `numpy.round` but the problem isn't really with `round`, it's that something that should be a `float` is actually a `numpy.ndarray`.  The question is why `numpy.max` on a 1D array is producing a (presumably single element) `numpy.ndarray` instead of a `float`.

The third issue I have had no time to look into.

**Comment by czender** [comment]
Regarding the valid_range issue: valid_range should obviously be a [min,max] pair of numbers not a text string. This is probably an oversight by whomever created the CERES-EBAF observational climatology. Pinging @glpotter and @susburrows to see if they can fix this upstream. Removing the valid_range attribute complete will probably also fix the issue. And "degrees_south" is not a recognized unit in CF anyway.

**Comment by susburrows** [comment]
Commenting here to let you know I have seen this!  I will try to see if I can find someone who has time to fix this valid_range issue in the obs.  Is this urgent?

**Comment by xylar** [comment]
@susburrows, thank you for keeping this on your radar. I don't think it's terribly urgent but it might be nice to have it dealt with in the next month and a half or so.  @salilmahajan, would you agree?

**Comment by susburrows** [comment]
@xylar and @czender , I just had a quick look to remind myself what is going on here.  First, just wanted to confirm whether you are using the E3SM svn repo (the obs_for_diagnostics directory)?

In that directory, there are several versions of the CERES-EBAF dataset.  The one with file names CERES-EBAF* is deprecated.  This is a ten-year climatology of CERES-EBAF, originally produced by Cecile Hannay in 2011 for the AMWG diagnostics, and updated slightly by me in April 2015 to address some issues in compliance with CF and ACME conventions (correcting a typo in units, adding time_bnds and climatology_bnds, making the time axis contain dates instead of integers, and correcting a typo in some of the unit definitions).

It would be straightforward to fix this.  However, what I would recommend you do instead is switching to the newer dataset that Mike Depuy, a student working with me on this, generated in June 2015, which is called CERES_EBAF-TOA*.  The new file uses 15 years of CERES-EBAF data instead of 10 (since it was produced several years later when more data had been collected), and it fixes the issue with valid_range that you have identified.  It also has floating point values for valid_min and valid_max attributes, instead of strings, and possibly some other small fixes to CF compliance (Mike used a CF compliance checker to validate compliance).  Finally, it has better provenance, as the git hash of the processing script, which contains all processing done after acquiring the dataset has been documented in the netCDF global attributes.

**Comment by xylar** [comment]
Thanks @susburrows, all of this seems very helpful.  @salilmahajan and @kevans32, these details seem much more in your wheelhouse.  I know things are busy right now.  Could you take a look at this when you have time?

**Comment by salilmahajan** [comment]
I think it would be best to go with Susannah's suggestion. We should point to the new CERES_EBAF-TOA files. I will fix this soon (during AGU).

**Comment by milenaveneziani** [comment]
@salilmahajan: is the problem discussed here now solved?

**Comment by xylar** [comment]
If we end up moving a-prime's unique capabilities gradually over to e3sm_diags, I think that would be the time to make the transition to python 3.  If we're not going to include a-prime as a conda package in e3sm-unified, there's no pressing need to support python 3.

**Pull request closed without merging**
